export default [
  {
    ignores: ["node_modules/**", "dist/**"],
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        AudioContext: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        Element: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        TouchEvent: "readonly",
        MouseEvent: "readonly",
        PointerEvent: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        Worker: "readonly",
        URL: "readonly",
        fetch: "readonly",
        Image: "readonly",
        Path2D: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        crypto: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        Infinity: "readonly",
        NaN: "readonly",
        undefined: "readonly",
        globalThis: "readonly",
        structuredClone: "readonly",
        queueMicrotask: "readonly",
        Audio: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        self: "readonly",
        OffscreenCanvas: "readonly",
        Node: "readonly",
        HTMLImageElement: "readonly",
        CSS: "readonly",
        SVGElement: "readonly",
      }
    },
    rules: {
      "no-unused-vars": ["warn", {
        "varsIgnorePattern": "^_",
        "argsIgnorePattern": "^_",
        "caughtErrorsIgnorePattern": "^_"
      }],
      "no-undef": "warn",
      "no-redeclare": "error",
      "no-unreachable": "warn",
      "no-duplicate-case": "error",
      "no-extra-semi": "warn",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "valid-typeof": "error",
      "no-constant-condition": "warn",
      "no-debugger": "warn",
      "no-empty": "warn",
    }
  },
  {
    files: ["electron/**/*.cjs", "scripts/**/*.cjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        __dirname: "readonly",
        console: "readonly",
        process: "readonly",
        require: "readonly",
      },
    },
  }
];
